language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: samanthakoski-github
    token:
      secure: 9ef2b6778b64ee981933dfa02e590e9a48e84a9c
jdk: 
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
